### ISSUE TITLE
"node_type" and "target_attribute" parameters are not being passed to nai_splitter_plugin

### ISSUE THREAD

**Issue by youph** [data61/stellar-evaluation-plugins#12] opened 2018-02-01 07:51 UTC
When running a pipeline with just the data splitter in it, and posting the following POST request to nai_scheduler_plugin:
```
curl -i http://0.0.0.0:5000/nai_scheduler/ -H "Content-Type: application/json" -X POST -d '{"inputs":{ "in_data": { "epgm_directory": "~/Projects/Graph_Analytics/data/wiki/wiki.epgm/", "pipeline_filename": "~/Projects/Graph_Analytics/code/stellar-evaluation-plugins/stellar-config/pipeline_splitter.json", "dataset_name": "wiki"}}, "output":"pred/", "parameters": {"target_attribute": "subject", "convert_epgm": "false"} }'
```
I noticed that the "node_type" and "target_attribute" parameters are not being passed to nai_splitter_plugin, since it prints this:

```
[2018-02-01 18:47:46,712: INFO/ForkPoolWorker-5] Splitter task started with args: {'num_samples_per_class': 100, 'test_size': 100000}
[2018-02-01 18:47:46,712: INFO/ForkPoolWorker-5] Inputs: {'in_data': {'vertex_labels_filename': '/Users/tys017/Projects/Graph_Analytics/data/wiki/wiki.epgm/pred/temp/wiki.lab', 'dataset_name': 'wiki'}}
[2018-02-01 18:47:46,713: WARNING/ForkPoolWorker-5] Please specify node type
[2018-02-01 18:47:46,713: WARNING/ForkPoolWorker-5] Please specify target attribute
[2018-02-01 18:47:46,714: WARNING/ForkPoolWorker-5] **************
[2018-02-01 18:47:46,714: WARNING/ForkPoolWorker-5] node type None and target attribute None
[2018-02-01 18:47:46,715: WARNING/ForkPoolWorker-5] **************

```

**Comment by PantelisElinas** [comment] 2018-02-01 21:47
I think that you might be using an older version of the code.

Also, your POST request does not specify the node_type just target_attribute.

Finally, the node_type and target_attribute in nai_scheduler_plugin are used for the call to convert_from_epgm() and are not passed to data splitter by design. For the data splitter you have to specify these two in the parameters section in the .json pipeline configuration file.

 "parameters": 
 {
 	"data splitter": {"target_attribute": ["subject"], "node_type":["paper"], "num_samples_per_class": [20], "test_size": [1000]},
 	"inference": {"method": ["logistic"]}, 
 	"representation": {"q": [1.0], "p": [1.0]}
 }

**Comment by PantelisElinas** [comment] 2018-02-01 21:58
Ignore my comment that you might be using older version of the code. This is definitely not the case.

**Comment by youph** [comment] 2018-02-01 23:43
I see the reason now; however, this is quite confusing to use: instead of sending a POST request to nai_scheduler_plugin (say, from the coordinator) with node type and target attribute specified in the request for all possible pipelines, a user needs to think really hard where to specify those, in the POST request, or in the pipeline config file. Don't you think?

**Comment by PantelisElinas** [comment] 2018-02-01 23:57
Anyway, there reason it is this way has to do with the fact that the scheduler plugin cannot be part of a pipeline and it ignores the parameters section in the .json pipeline config file (as, in it passes the values on to the plugins but doesn't look at them in detail) because this way we can add or remove "parameters" for a plugin and the scheduler keeps working.

There is a way around this but not currently supported by the scheduler. You would have to use the epgm_converter and epmg_writer tasks from nai_epgm_plugin.py in the pipeline and specify the target_attribute and node_type in their parameters section. Since the scheduler would not have to call its own convert_from_epgm() function, it would not have to know these two values.

**Comment by youph** [comment] 2018-02-02 00:00
Ok, the way with the scheduler calling nai_epgm_plugin makes sense, I think. Then the node type and target attribute would be specified in the pipeline config only, but not in the call to the scheduler?

**Comment by PantelisElinas** [comment] 2018-02-02 01:03
Yes, as we discussed, this would be the case.

I'll close this issue for now.

**Closed** 2018-02-02 01:04 UTC
Labels: bug
